### ISSUE TITLE
Errors from discovery v5

### ISSUE THREAD

**Issue by ajsutton** [ConsenSys/discovery#59]
From Nishant on Prysm discord:
Occasionally Teku has difficulty peering with Prysm locally. It seems like a discoveryV5 issue 
https://gist.github.com/nisdas/24fa1fc59c1b2ea37143a4abcab4e0d5
I am just running a local testnet with it and it came up

**Comment by cemozerr** [comment]
P3. Adding the bug label here due to Discovery repo not having bug labels yet.
